import streamlit as st
from transformers import pipeline
from PIL import Image

# Set page title and favicon
st.set_page_config(page_title="Summarizer", page_icon=":memo:", layout="wide")

# Set app title
st.title("BriefMe")

# Add header and divider
st.subheader("Your personal AI-powered summarizer")
st.markdown("---")

# Define app layout
left_column, right_column = st.columns([3, 2])

with left_column:
    # Add text input box
    input_text = st.text_area("Input text you want to summerize", height=300)

    # Add "Summarize" button
    if st.button("Summarize"):
        # Initialize the summarization pipeline
        summarizer = pipeline("summarization", model="facebook/bart-large-cnn",
                              framework='pt', device=-1)  # 0 for gpu and -1 for cpu

        # Call the summarization function
        result = summarizer(input_text[:2400], max_length=1024,
                            min_length=30, do_sample=False)

        # Display the summarized text
        st.success("Here's the summary:")
        st.write(result[0]['summary_text'])

with right_column:
    # Add section header and divider
    st.subheader("Additional Information")
    "Turn your long reads into short reads with our Summarizer app."
    "Simply type in any text you want, click the magic 'Summarize' button, and voila! Let our powerful AI model distill the most important parts of your text into a concise and easy-to-read summary."
    "No more reading lengthy articles or reports - let our Summazing wizard do the hard work for you!"
    st.markdown("---")

    # Add links
    st.markdown("### Links")
    st.markdown("[Streamlit Homepage](https://streamlit.io/)")
    st.markdown("[Huggingface Homepage](https://huggingface.co)")

    # Add emoji
    st.markdown("### Emoji")
    st.write(":sunglasses: :tada: :fire: :rocket: :sparkles:")

    # Add image
    image = Image.open(r"static/star.jpg")
    st.image(image, use_column_width=True)

# Add footnote with disclaimer
st.markdown("""
            *Disclaimer: This app is for educational and informational purposes only. 
            The results provided by the app are generated by a machine learning model and should not be taken as professional advice. 
            The app does not guarantee the accuracy, completeness, or reliability of the summarized text. 
            Use the app at your own discretion. 
            We do not store your data or sell it to third parties*
            """)
